/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.vaydeal.partner.validation;

import com.vaydeal.partner.intfc.validation.Validation;
import com.vaydeal.partner.message.CorrectMsg;
import com.vaydeal.partner.message.ErrMsg;
import com.vaydeal.partner.req.mod.ForgotPassword;

/**
 * @company techvay
 * @author rifaie
 */
public class ForgotPasswordValidation implements Validation{
    
    private final ForgotPassword req;
    private String paramValue = "";
    private String paramName = "";

    public ForgotPasswordValidation(ForgotPassword ve) {
        this.req = ve;
    }

    @Override
    public void validation() throws Exception {
        ForgotPasswordConstraints reqc = new ForgotPasswordConstraints(req);
        String valid = "";
        valid += reqc.validateUID();
        valid += "#"+reqc.validateEmail();
        int count = 0;
        for (String str : valid.split("#")) {
            paramName += str.split(" ")[1].toLowerCase() + "#";
            if (!str.startsWith(CorrectMsg.CORRECT_MESSAGE)) {
                count++;
                paramValue += str + "#";
            } else {
                paramValue += CorrectMsg.CORRECT_MESSAGE + "#";
            }
        }
        paramName += "reqValidation";
        if (count == 0) {
            req.setAutogeneratedValues();
            paramValue += CorrectMsg.CORRECT_FORGOT_PASSWORD;
        } else {
            paramValue += ErrMsg.ERR_FORGOT_PASSWORD;;
        }
    }
    
    @Override
    public String toString() {
        String[] paramsN = paramName.split("#");
        String[] paramV = paramValue.split("#");
        String json = "";
        for (int i = 0; i < paramsN.length; i++) {
            json += "\"" + paramsN[i] + "\"" + ":" + "\"" + paramV[i] + "\" ,";
        }
        json = json.substring(0, json.length() - 1);
        return "{" + json + "}";
    }
    

}
